### ISSUE TITLE
Browse files link to include images in comments is not showing

### ISSUE THREAD

**Issue by leokury** [dylantientcheu/urplus#1]
The link of browse files to include some image in comments is not showing while the extension is activated.

![udacity reviews 5](https://user-images.githubusercontent.com/620050/30935297-9ac33bba-a3a6-11e7-8f56-0e917f78db0c.png)

**Comment by michaelhays** [comment]
Right, I forgot I had removed that when I first started building this. I solely drag and drop images so it wasn't useful to me. I'll add it back in

**Comment by leokury** [comment]
Sometimes I use drag and drop feature and sometimes I choose some file. I think that the link should still there. Maybe just one more button after CANCEL button?

**Comment by michaelhays** [comment]
That's a good idea, I'll probably add that in the near future. For now I'm just going to redisplay the "Browse files" caption because you're right, many people likely use it.
