### ISSUE TITLE
How to stop the process?

### ISSUE THREAD

**Issue by BoPengGit** [dylantientcheu/urplus#11]
Hi Michael,

Do you know how to stop the queue? It seems like when I shut down my computer and everything, the queue continues to go on. How do I uninstall the program and not let it run anymore?

Thank you for this project you built!

**Comment by michaelhays** [comment]
Hey Bo, if you flip the switch at the top right of the popup to off, the app will stop assigning. Let me know if you have any issues with this.

**Comment by BoPengGit** [comment]
Thanks Michael!

Awesome work.
