### ISSUE TITLE
Suggestion: Currency converter on click

### ISSUE THREAD

**Issue by dylantientcheu** [dylantientcheu/urplus#13]
I know this is more like an enhancement, 
but it will be awesome if we could click to convert to a specific currency.

**Comment by michaelhays** [comment]
What currencies would you like to see? And I assume you mean in the popup window?

**Comment by dylantientcheu** [comment]
Yes, I actually mean in the popup window, maybe we can select through many currencies, however for me
I think the main currencies will be great, `EUR, GPB, XAF, USD, AUD, AED, INR.`
I can submit a pull request to help with that if possible.

**Comment by michaelhays** [comment]
No worries, I can build it now and ship it later this evening.

Do you know if the Udacity API responds with USD regardless of the reviewer's region? I use the `/me/submissions/completed.json?start_date=...` endpoint to calculate daily and monthly earnings.

**Comment by dylantientcheu** [comment]
Alright...

And yes it does responds with USD regardless.

I'd like to point out too that, the monthly earnings currently on the popup is a little bit more than the one on the new dashboard. It maybe because of the dashboard change.

**Comment by michaelhays** [comment]
The monthly earnings are calculated by UTC-month-to-date in the popup. To my knowledge, this is the window that Udacity uses to determine monthly payout. I just looked on the mentor dashboard, and they call `https://review-api.udacity.com/api/v1/me/submissions/completed.json?start_date=2018-02-01T00:00:00-06:00&end_date=2018-02-27T23:59:59-06:00` for the monthly earnings (-06:00 matches my timezone).

They may have changed payment periods from UTC-month to localized-month. Or, more likely, they accidentally used the localized month start in the mentor dashboard when they meant to use UTC month start. When February payments arrive, if anyone can confirm that the payout window uses the localized month, I'll change it in the popup.
