### ISSUE TITLE
Beautiful Design is gone :(

### ISSUE THREAD

**Issue by dylantientcheu** [dylantientcheu/urplus#14]
Since the Udacity dashboard update, the beautiful design that existed previously is gone and this is what is left. I do not know it if I'm the only one having this issue.

![screenshot_1](https://user-images.githubusercontent.com/26802924/36755412-6bcb7a14-1c0c-11e8-90d8-b94ea7394242.png)

**Comment by michaelhays** [comment]
The popup has had this design since I removed the Remote Assignment functionality a few weeks ago. Feel free to pretty it up in a pull request, if you'd like

**Comment by dylantientcheu** [comment]
I forked the project and did this.
I can send it here if accepted.
I'm also open to any critics.

Also you can see 3hours ago on the time column, I added momentjs on another commit and I am able to take time elapsed.

### No Review Assigned

![screenshot_4](https://user-images.githubusercontent.com/26802924/37041838-63e2237e-215d-11e8-94f9-3ca4711cfe2b.png)

### Review Assigned
![ux](https://user-images.githubusercontent.com/26802924/37039988-16017b4a-2159-11e8-85b5-2b43e09daff2.gif)

**Comment by michaelhays** [comment]
Looks great! Can you create a pull request on this repo?
