### ISSUE TITLE
Load remarks for previously passed rubric items

### ISSUE THREAD

**Issue by WittmannF** [dylantientcheu/urplus#19]
Recently there was a new update in the platform where rubric items which are approved by a reviewer are locked and are not allowed for changes in the resubmission:

![screen shot 2018-03-12 at 20 20 10](https://user-images.githubusercontent.com/5733246/37302000-e5ffcf62-2632-11e8-9c19-9437e43932ac.png)

The remarks are not loading for those rubric items.

**Comment by dylantientcheu** [comment]
This is because the classes and ids of elements @michaelhays used are being overrided by the new ones.
When these come up. I usually leave them that way.
So you need to add the remarks even on these previously passed ones ?

**Comment by WittmannF** [comment]
Yes, I would like to load the 'Meet Specs' remarks for those rubric items. We have the requirement of minimum 5 comments per review, and I usually add some bonus comments in the resubmission.
