### ISSUE TITLE
Extension not works with the new API

### ISSUE THREAD

**Issue by brenopolanski** [dylantientcheu/urplus#21]
Could remove it :point_down:

![screenshot from 2018-06-04 10-24-23](https://user-images.githubusercontent.com/1894191/40919980-97f7bf5a-67e1-11e8-89c5-975bc784cbb5.png)

**Comment by dylantientcheu** [comment]
Yes, we should... is there anything you’d like to replace that ?

Or we should just let it empty ?

**Comment by brenopolanski** [comment]
No, just remove it! I'll send a PR :)

**Comment by dylantientcheu** [comment]
Alright 👌🏽
