### ISSUE TITLE
Suggestion: make it possible to consult past critiques while writing a new one

### ISSUE THREAD

**Issue by leokury** [dylantientcheu/urplus#3]
It would be interesting that we could consult the critiques already registered while writing a new one without replacing the current text. So we can copy some passages and consult links that apply also to the current critique.

**Comment by michaelhays** [comment]
Yes, this would be useful. I'd like to keep this out of the extension for simplicity's sake, but eventually, I'm going to add a section in https://urplus.herokuapp.com that will display a grid of all of your remarks. Something like this, but with a better UI (screenshot is from my old app that I used for reviewing):

![selection_001](https://user-images.githubusercontent.com/6445661/30992189-3cfe2c88-a46e-11e7-9609-23795b4e5fb5.png)

And then, when you click on one of the remarks, it will show the content:

![selection_002](https://user-images.githubusercontent.com/6445661/30992193-480dd72c-a46e-11e7-9aa6-d335de90451d.png)

Does this achieve what you were thinking?

**Comment by leokury** [comment]
How about using the extension Panel to show all recorded remarks of the item currently being edited?

So when editing some rubric's item we can click on extension icon and it shows all recorded remarks of that item.

![urplus suggestion](https://user-images.githubusercontent.com/620050/31101085-9493575c-a7a2-11e7-9ef0-72ce789b244f.png)

**Comment by michaelhays** [comment]
Are you envisioning using this for just critiques, and not for comments or general comments?

If so, I'll probably just add a critique-specific dropdown box, like so (bottom right):

![selection_001](https://user-images.githubusercontent.com/6445661/31107683-d276fa26-a7b9-11e7-821e-489413286ace.png)

Then in the expanded area, it would list all the critiques for that criterion in the style of the filtered critiques, ordered by number of retrievals. The page would pop up the critique body text when you click on each critique.

**Comment by leokury** [comment]
Sure! I think that would help a lot with the critiques and general comments!
