### ISSUE TITLE
What should I learn in order to contribute

### ISSUE THREAD

**Issue by WittmannF** [dylantientcheu/urplus#46]
Hello, I started learning javascript and yesterday I learned the very basics for creating a chrome extension with this tutorial: https://developer.chrome.com/extensions/getstarted

However, Urplus is waay another level. I coudn't understand anything when I was checking the source code. My field is data science, so I am more comfortable with python. The source code seems to be a mix of Python and JS. 

I would love to get suggestions of materials or topics that I should learn in order to understand the source code, and eventually, contribute as well. 

Thanks!

**Comment by dylantientcheu** [comment]
UrPlus is written in [VueJS](https://vuejs.org/) in front end and Python in backend. 
Anything dealing with the interaction between the extension and the browser is written in VueJS.
To acquire a good touch at that, I'll suggest you to get along with front end tools first... then understand how VueJS helps create interfaces, after that, you'll be good to go.
