### ISSUE TITLE
Would like to contribute for mobile development

### ISSUE THREAD

**Issue by shivasurya** [dylantientcheu/urplus#7]
I'm Shivasurya from India and would like to contribute for mobile development notification/extension.

Can we discuss about it ?

**Comment by michaelhays** [comment]
Hey Shivasurya, can you message me in the Slack group? My username is michaelhays

**Comment by shivasurya** [comment]
slack group url ?

**Comment by michaelhays** [comment]
https://udacitymentors.slack.com

**Comment by shivasurya** [comment]
Looks like I dont have access to it.
https://twitter.com/sshivasurya can you ping me for hangout chat ?
